# Site settings
title: Freelancer
email: mittalmailbox@gmail.com
url: https://amitmittal.xyz
description: "Professional web designer & front-end developer with extensive experience building websites using AngularJS, HTML5, CSS3 and various web scripting technologies, web standards and project management.Enthusiastic web professional motivated by challenging projects and deadlines."
skills: "Web Developer - Mobile Developer - User Experience Designer"
meta_author: Kumar Amit

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
#Â - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: Amit

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Amit Kumar
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/Ak_mittal
  - title: facebook
    url: https://www.facebook.com/akmittal91
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/amit_mittal
  - title: github
    url: http://github.com/akmittal

# Postal address (add as many lines as necessary)
address:
  - line: Whitefield
  - line: Bangalore, 560037

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
